name: datly_client
description: Client for the Datly project.
publish_to: none

environment:
  sdk: ^3.10.1
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  auto_route: ^11.0.0
  shared_preferences: ^2.5.3
  http: ^1.6.0
  image: ^4.5.4
  camera: ^0.11.3
  blurhash_dart: ^1.2.1
  url_launcher: ^6.3.2
  mime: ^2.0.0
  get_time_ago: ^2.3.2
  markdown_widget: ^2.3.2+8
  file_picker: ^10.3.8

dev_dependencies:
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: GoogleSansCode
      fonts:
        - asset: assets/fonts/GoogleSansCode-Bold.ttf
  assets:
    - assets/icon.png
    - assets/OFL.txt
