name: datly_server
description: Server for the Datly project.
publish_to: none

environment:
  sdk: ^3.9.2
resolution: workspace

dependencies:
  datly: any
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_multipart: ^2.0.1
  shelf_limiter: ^2.0.1
  tracer: ^0.4.2
  mime: ^2.0.0
  dotenv: ^4.2.0
  uuid: ^4.5.2
  drift: ^2.30.0
  sqlite3: ^2.9.3
  image: ^4.5.4
  blurhash_dart: ^1.2.1
  archive: ^4.0.7
  http: ^1.6.0
  cryptography: ^2.9.0
  dart_jsonwebtoken: ^3.3.1
  retry: ^3.1.2
  mailer: ^6.6.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4
  intl_translation: ^0.21.0
